import { ThemeProvider } from "@/components/Provider/ThemeProvider";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs"

import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import DialogProvider from "@/components/Provider/DialogProvider";
import { DrawerForm } from "@/components/Forms/DrawerForm";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <ClerkProvider>
          <body className={cn("w-full h-full", inter.className)}>
            <Navbar />
            {children}
            <DialogProvider />
          </body>
        </ClerkProvider>
      </ThemeProvider>

    </html>
  );
}
