import { ThemeProvider } from "@/components/Provider/ThemeProvider";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs"

import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import DialogProvider from "@/components/Provider/DialogProvider";
import { DrawerForm } from "@/components/Forms/DrawerForm";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
      <html lang="en" suppressHydrationWarning >
        <body className={cn("w-full ", inter.className)}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <DialogProvider />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
